#!/bin/bash

VERSION=0.2.0

export CC=gcc

rm -f roswell/12forks
ros build roswell/12forks.ros
mv roswell/12forks roswell/12forks-osx-$VERSION

docker run --rm -ti -v `pwd`:/app 12forks-roswell bash -c 'cd /app && ros build roswell/12forks.ros'
mv roswell/12forks roswell/12forks-debian-ubuntu-$VERSION
